
const memberData = [
  {
    userName: '野生小黄鱼゛',
    position: '二当家',
    occupation: '铁衣',
    combatPower: '323903',
  },
  {
    userName: '慕欢欢',
    position: '五当家',
    occupation: '潮光',
    combatPower: '324627',
  },
  {
    userName: '祝卿安',
    position: '轩辕副堂主',
    occupation: '素问',
    combatPower: '320831',
  },
  {
    userName: '文清歌',
    position: '惊鸿堂众',
    occupation: '神相',
    combatPower: '317796',
  },
  {
    userName: '今晚夜色真美゜',
    position: '惊鸿堂众',
    occupation: '鸿音',
    combatPower: '327451',
  },
  {
    userName: '阿默゜',
    position: '惊鸿堂众',
    occupation: '素问',
    combatPower: '322981',
  },
  {
    userName: '菁菁子芯',
    position: '惊鸿堂众',
    occupation: '素问',
    combatPower: '326745',
  },
  {
    userName: '乄你默笑灬',
    position: '惊鸿堂众',
    occupation: '神相',
    combatPower: '326341',
  },
  {
    userName: '白秋丶',
    position: '惊鸿堂众',
    occupation: '素问',
    combatPower: '327647',
  },
  {
    userName: '番茄松鼠鱼',
    position: '惊鸿堂众',
    occupation: '血河',
    combatPower: '326585',
  },
  {
    userName: '偏執',
    position: '惊鸿堂众',
    occupation: '龙吟',
    combatPower: '322273',
  },
  {
    userName: '黄泉之烬',
    position: '星愿堂众',
    occupation: '潮光',
    combatPower: '325599',
  },
  {
    userName: '青阳语嫣',
    position: '星愿堂众',
    occupation: '潮光',
    combatPower: '324265',
  },
  {
    userName: '一杆大铁枪',
    position: '星愿堂众',
    occupation: '血河',
    combatPower: '326089',
  },
  {
    userName: '风之枷锁',
    position: '绝影堂众',
    occupation: '潮光',
    combatPower: '324454',
  },
  {
    userName: '潮光空悠悠',
    position: '绝影堂众',
    occupation: '潮光',
    combatPower: '326612',
  },
  {
    userName: '现捞海胆',
    position: '绝影堂众',
    occupation: '神相',
    combatPower: '321006',
  },
  {
    userName: '辰雾ゞ',
    position: '绝影堂众',
    occupation: '荒羽',
    combatPower: '320792',
  },
  {
    userName: '芊小荨',
    position: '绝影堂众',
    occupation: '神相',
    combatPower: '318897',
  },
  {
    userName: '少帥゛',
    position: '绝影堂众',
    occupation: '九灵',
    combatPower: '326020',
  },
  {
    userName: '爱弹琴的磊磊',
    position: '绝影堂众',
    occupation: '神相',
    combatPower: '318562',
  },
  {
    userName: '予星',
    position: '绝影堂众',
    occupation: '碎梦',
    combatPower: '325613',
  },
  {
    userName: '祝星',
    position: '绝影堂众',
    occupation: '素问',
    combatPower: '325942',
  },
  {
    userName: '夜崽崽ぃ',
    position: '绝影堂众',
    occupation: '神相',
    combatPower: '326325',
  },
  {
    userName: '波罗丁丶',
    position: '绝影堂众',
    occupation: '碎梦',
    combatPower: '325319',
  },
  {
    userName: '锖青磁゜',
    position: '轩辕堂众',
    occupation: '潮光',
    combatPower: '323035',
  },
  {
    userName: '鸿城',
    position: '轩辕堂众',
    occupation: '潮光',
    combatPower: '318394',
  },
  {
    userName: '乐优゜',
    position: '轩辕堂众',
    occupation: '素问',
    combatPower: '319519',
  },
  {
    userName: '小翠花儿',
    position: '轩辕堂众',
    occupation: '碎梦',
    combatPower: '326069',
  },
  {
    userName: '华流ペ坤曲',
    position: '轩辕堂众',
    occupation: '血河',
    combatPower: '326714',
  },
  {
    userName: '心蕊',
    position: '轩辕堂众',
    occupation: '素问',
    combatPower: '323697',
  },
  {
    userName: '晓晓屹丷',
    position: '帮众',
    occupation: '潮光',
    combatPower: '320881',
  },
  {
    userName: '胖头鱼又饿了',
    position: '帮众',
    occupation: '鸿音',
    combatPower: '318412',
  },
  {
    userName: '取个名字真难啊',
    position: '帮众',
    occupation: '潮光',
    combatPower: '325413',
  },
  {
    userName: '依依ン',
    position: '帮众',
    occupation: '素问',
    combatPower: '326566',
  },
  {
    userName: '当麻',
    position: '帮众',
    occupation: '潮光',
    combatPower: '321059',
  },
  {
    userName: '春风将晚丶',
    position: '帮众',
    occupation: '玄机',
    combatPower: '324174',
  },
  {
    userName: '月灼',
    position: '帮众',
    occupation: '碎梦',
    combatPower: '320254',
  },
  {
    userName: '硬棒棒的奶',
    position: '帮众',
    occupation: '素问',
    combatPower: '308707',
  },
  {
    userName: '不念过往丶',
    position: '帮会学徒',
    occupation: '潮光',
    combatPower: '320281',
  },
  {
    userName: '陈青衣丷',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '290424',
  },
  {
    userName: '若心',
    position: '帮会学徒',
    occupation: '铁衣',
    combatPower: '313793',
  },
  {
    userName: '甜妹吖',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '310615',
  },
  {
    userName: '这一套你敢吃吗',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '310938',
  },
  {
    userName: '繁花',
    position: '帮会学徒',
    occupation: '鸿音',
    combatPower: '319477',
  },
  {
    userName: '伍什么怡',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '302866',
  },
  {
    userName: '序曲',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '317605',
  },
  {
    userName: '夜魅ゞ',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '323106',
  },
  {
    userName: '抱月剑',
    position: '大当家',
    occupation: '龙吟',
    combatPower: '327453',
  },
  {
    userName: '今日阳光明媚゜',
    position: '三当家',
    occupation: '铁衣',
    combatPower: '324413',
  },
  {
    userName: '゜我没有钱钱了',
    position: '四当家',
    occupation: '素问',
    combatPower: '318932',
  },
  {
    userName: '゛温栖',
    position: '尊堂主',
    occupation: '素问',
    combatPower: '303821',
  },
  {
    userName: '血河来喽',
    position: '惊鸿堂主',
    occupation: '九灵',
    combatPower: '323329',
  },
  {
    userName: '丷大瑾乔',
    position: '绝影副堂主',
    occupation: '素问',
    combatPower: '316961',
  },
  {
    userName: '小缥丶',
    position: '尊堂众',
    occupation: '铁衣',
    combatPower: '305963',
  },
  {
    userName: '若干',
    position: '归云堂众',
    occupation: '潮光',
    combatPower: '309795',
  },
  {
    userName: '悠小悠',
    position: '归云堂众',
    occupation: '素问',
    combatPower: '316248',
  },
  {
    userName: '薄暮凉',
    position: '归云堂众',
    occupation: '碎梦',
    combatPower: '325185',
  },
  {
    userName: '风也温柔゜',
    position: '惊鸿堂众',
    occupation: '素问',
    combatPower: '306460',
  },
  {
    userName: '皮克斯ぃ',
    position: '惊鸿堂众',
    occupation: '碎梦',
    combatPower: '321729',
  },
  {
    userName: '微梦最后的种子',
    position: '惊鸿堂众',
    occupation: '碎梦',
    combatPower: '317959',
  },
  {
    userName: '゛哇哦',
    position: '惊鸿堂众',
    occupation: '铁衣',
    combatPower: '324549',
  },
  {
    userName: '暮倾雪丶',
    position: '惊鸿堂众',
    occupation: '九灵',
    combatPower: '322930',
  },
  {
    userName: '张亦安',
    position: '惊鸿堂众',
    occupation: '神相',
    combatPower: '322148',
  },
  {
    userName: '凉水',
    position: '惊鸿堂众',
    occupation: '鸿音',
    combatPower: '319599',
  },
  {
    userName: '青萍',
    position: '惊鸿堂众',
    occupation: '素问',
    combatPower: '312167',
  },
  {
    userName: '萧潇霄笑笑',
    position: '惊鸿堂众',
    occupation: '血河',
    combatPower: '325841',
  },
  {
    userName: '穿心街小银龙ゞ',
    position: '惊鸿堂众',
    occupation: '潮光',
    combatPower: '320743',
  },
  {
    userName: '佾雲',
    position: '惊鸿堂众',
    occupation: '龙吟',
    combatPower: '324636',
  },
  {
    userName: '天赋异禀',
    position: '惊鸿堂众',
    occupation: '神相',
    combatPower: '320537',
  },
  {
    userName: '小小火龙',
    position: '惊鸿堂众',
    occupation: '龙吟',
    combatPower: '321855',
  },
  {
    userName: '゜我没有花花了',
    position: '星愿堂众',
    occupation: '铁衣',
    combatPower: '321683',
  },
  {
    userName: '笑南淡如风',
    position: '星愿堂众',
    occupation: '龙吟',
    combatPower: '320057',
  },
  {
    userName: '困昆想食饼',
    position: '星愿堂众',
    occupation: '铁衣',
    combatPower: '318093',
  },
  {
    userName: '祈念丶',
    position: '星愿堂众',
    occupation: '玄机',
    combatPower: '320890',
  },
  {
    userName: '澜亭',
    position: '星愿堂众',
    occupation: '荒羽',
    combatPower: '326063',
  },
  {
    userName: '萌妹ヾ',
    position: '星愿堂众',
    occupation: '九灵',
    combatPower: '318911',
  },
  {
    userName: '剧毒术士',
    position: '星愿堂众',
    occupation: '素问',
    combatPower: '313404',
  },
  {
    userName: '千尘丶',
    position: '星愿堂众',
    occupation: '九灵',
    combatPower: '318898',
  },
  {
    userName: '鱼忆七秒゜',
    position: '星愿堂众',
    occupation: '素问',
    combatPower: '310616',
  },
  {
    userName: '雨点点',
    position: '星愿堂众',
    occupation: '素问',
    combatPower: '324545',
  },
  {
    userName: '゜我没有糖糖了',
    position: '星愿堂众',
    occupation: '九灵',
    combatPower: '320593',
  },
  {
    userName: '゜我没有病病了',
    position: '星愿堂众',
    occupation: '玄机',
    combatPower: '313587',
  },
  {
    userName: '红包',
    position: '星愿堂众',
    occupation: '玄机',
    combatPower: '306946',
  },
  {
    userName: '無晴゛',
    position: '星愿堂众',
    occupation: '玄机',
    combatPower: '322258',
  },
  {
    userName: '醉梦轻舞',
    position: '绝影堂众',
    occupation: '潮光',
    combatPower: '317565',
  },
  {
    userName: '三道玲',
    position: '绝影堂众',
    occupation: '九灵',
    combatPower: '325176',
  },
  {
    userName: '可颂゛',
    position: '绝影堂众',
    occupation: '素问',
    combatPower: '318602',
  },
  {
    userName: '鹤舞吖゛',
    position: '绝影堂众',
    occupation: '素问',
    combatPower: '324860',
  },
  {
    userName: '小小无题',
    position: '绝影堂众',
    occupation: '神相',
    combatPower: '320909',
  },
  {
    userName: '咖啡不加糖',
    position: '绝影堂众',
    occupation: '鸿音',
    combatPower: '312422',
  },
  {
    userName: '笔下风月',
    position: '绝影堂众',
    occupation: '鸿音',
    combatPower: '315957',
  },
  {
    userName: '纸上玲珑',
    position: '绝影堂众',
    occupation: '潮光',
    combatPower: '325722',
  },
  {
    userName: '夜夜盼星落山',
    position: '绝影堂众',
    occupation: '神相',
    combatPower: '320531',
  },
  {
    userName: '兰亭序゛',
    position: '绝影堂众',
    occupation: '碎梦',
    combatPower: '321803',
  },
  {
    userName: '郭慕理',
    position: '绝影堂众',
    occupation: '神相',
    combatPower: '311384',
  },
  {
    userName: '晚风尽',
    position: '绝影堂众',
    occupation: '素问',
    combatPower: '325976',
  },
  {
    userName: '糖衣不甜',
    position: '绝影堂众',
    occupation: '素问',
    combatPower: '319493',
  },
  {
    userName: '思雨眠゛',
    position: '绝影堂众',
    occupation: '血河',
    combatPower: '326854',
  },
  {
    userName: '夜梵音゛',
    position: '轩辕堂众',
    occupation: '铁衣',
    combatPower: '322388',
  },
  {
    userName: '丿月光丶',
    position: '轩辕堂众',
    occupation: '铁衣',
    combatPower: '320990',
  },
  {
    userName: '寂寂远过',
    position: '轩辕堂众',
    occupation: '鸿音',
    combatPower: '320691',
  },
  {
    userName: '叁月灬',
    position: '轩辕堂众',
    occupation: '铁衣',
    combatPower: '319609',
  },
  {
    userName: '声声慢゜',
    position: '轩辕堂众',
    occupation: '九灵',
    combatPower: '318680',
  },
  {
    userName: '钻洞进雾呆呆鸟',
    position: '轩辕堂众',
    occupation: '神相',
    combatPower: '321119',
  },
  {
    userName: '小柒柒儿',
    position: '轩辕堂众',
    occupation: '玄机',
    combatPower: '322261',
  },
  {
    userName: '觉夏゛',
    position: '轩辕堂众',
    occupation: '素问',
    combatPower: '312627',
  },
  {
    userName: '紷鳶゜',
    position: '轩辕堂众',
    occupation: '素问',
    combatPower: '314900',
  },
  {
    userName: '小泡芙儿',
    position: '轩辕堂众',
    occupation: '素问',
    combatPower: '325600',
  },
  {
    userName: '一颗苹果丶',
    position: '轩辕堂众',
    occupation: '血河',
    combatPower: '324544',
  },
  {
    userName: '淡紫色',
    position: '轩辕堂众',
    occupation: '神相',
    combatPower: '320650',
  },
  {
    userName: '馨语',
    position: '轩辕堂众',
    occupation: '素问',
    combatPower: '310775',
  },
  {
    userName: '徐盼盼',
    position: '轩辕堂众',
    occupation: '神相',
    combatPower: '325690',
  },
  {
    userName: '阿凌丷',
    position: '轩辕堂众',
    occupation: '血河',
    combatPower: '324982',
  },
  {
    userName: '白衣墨染尘',
    position: '轩辕堂众',
    occupation: '神相',
    combatPower: '320864',
  },
  {
    userName: '极致人生',
    position: '轩辕堂众',
    occupation: '血河',
    combatPower: '324083',
  },
  {
    userName: '祈今朝',
    position: '轩辕堂众',
    occupation: '九灵',
    combatPower: '327489',
  },
  {
    userName: '酸酸柠',
    position: '轩辕堂众',
    occupation: '素问',
    combatPower: '324566',
  },
  {
    userName: '゜我没有果果了',
    position: '帮众',
    occupation: '潮光',
    combatPower: '312057',
  },
  {
    userName: '゜我没有命命了',
    position: '帮众',
    occupation: '玄机',
    combatPower: '324217',
  },
  {
    userName: '通灵魔法师',
    position: '帮众',
    occupation: '潮光',
    combatPower: '323871',
  },
  {
    userName: '风之极ミ陨杀',
    position: '帮众',
    occupation: '潮光',
    combatPower: '320724',
  },
  {
    userName: '泡泡圈',
    position: '帮众',
    occupation: '潮光',
    combatPower: '317000',
  },
  {
    userName: '葉高兴',
    position: '帮众',
    occupation: '血河',
    combatPower: '318573',
  },
  {
    userName: '九朔',
    position: '帮众',
    occupation: '鸿音',
    combatPower: '323404',
  },
  {
    userName: '橘枝栀',
    position: '帮众',
    occupation: '素问',
    combatPower: '320757',
  },
  {
    userName: '胖头鱼゛',
    position: '帮众',
    occupation: '九灵',
    combatPower: '318771',
  },
  {
    userName: '木头马尾',
    position: '帮众',
    occupation: '血河',
    combatPower: '322601',
  },
  {
    userName: '鸽戈ぃ',
    position: '帮众',
    occupation: '九灵',
    combatPower: '325173',
  },
  {
    userName: '神荼゛',
    position: '帮众',
    occupation: '潮光',
    combatPower: '321261',
  },
  {
    userName: '业火四灾い',
    position: '帮众',
    occupation: '血河',
    combatPower: '324612',
  },
  {
    userName: '子礼',
    position: '帮众',
    occupation: '素问',
    combatPower: '312538',
  },
  {
    userName: '夜魅',
    position: '帮众',
    occupation: '玄机',
    combatPower: '326098',
  },
  {
    userName: '云苓ゝ',
    position: '帮众',
    occupation: '潮光',
    combatPower: '319638',
  },
  {
    userName: '诡计多端异乡人',
    position: '帮众',
    occupation: '素问',
    combatPower: '314620',
  },
  {
    userName: '酥米露',
    position: '帮众',
    occupation: '素问',
    combatPower: '319891',
  },
  {
    userName: '布丁魔法师',
    position: '帮众',
    occupation: '铁衣',
    combatPower: '325748',
  },
  {
    userName: '奈朵儿ぇ',
    position: '帮众',
    occupation: '素问',
    combatPower: '320524',
  },
  {
    userName: '决月',
    position: '帮众',
    occupation: '神相',
    combatPower: '315760',
  },
  {
    userName: '细辛ゝ',
    position: '帮会学徒',
    occupation: '血河',
    combatPower: '308871',
  },
  {
    userName: '囍气满满',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '310337',
  },
  {
    userName: '月灵灵',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '310693',
  },
  {
    userName: '我不睡一点',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '306864',
  },
  {
    userName: '青丝绕指柔',
    position: '帮会学徒',
    occupation: '碎梦',
    combatPower: '304840',
  },
  {
    userName: '上官青衣',
    position: '帮会学徒',
    occupation: '潮光',
    combatPower: '311941',
  },
  {
    userName: '小巷深深深几许',
    position: '帮会学徒',
    occupation: '潮光',
    combatPower: '302462',
  },
  {
    userName: '拾叁゛',
    position: '帮会学徒',
    occupation: '铁衣',
    combatPower: '314117',
  },
  {
    userName: '小桔烟丶',
    position: '帮会学徒',
    occupation: '潮光',
    combatPower: '311173',
  },
  {
    userName: '陌殇',
    position: '帮会学徒',
    occupation: '九灵',
    combatPower: '305006',
  },
  {
    userName: '珞珞大魔王',
    position: '帮会学徒',
    occupation: '血河',
    combatPower: '301605',
  },
  {
    userName: '晶羽魔法师',
    position: '帮会学徒',
    occupation: '潮光',
    combatPower: '322188',
  },
  {
    userName: '不是青年',
    position: '帮会学徒',
    occupation: '鸿音',
    combatPower: '307598',
  },
  {
    userName: '憮訫',
    position: '帮会学徒',
    occupation: '铁衣',
    combatPower: '315193',
  },
  {
    userName: '惊芸芸',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '307056',
  },
  {
    userName: '浮世清欢乀',
    position: '帮会学徒',
    occupation: '潮光',
    combatPower: '303979',
  },
  {
    userName: '曲秀才',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '298419',
  },
  {
    userName: '闭眼睛玩',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '300901',
  },
  {
    userName: '慕容睿',
    position: '帮会学徒',
    occupation: '血河',
    combatPower: '300353',
  },
  {
    userName: '星期日',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '324598',
  },
  {
    userName: '朝雪',
    position: '帮会学徒',
    occupation: '鸿音',
    combatPower: '311216',
  },
  {
    userName: '花满天朵朵',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '303024',
  },
  {
    userName: '池鱼お',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '313678',
  },
  {
    userName: '神弥粒゛',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '305409',
  },
  {
    userName: '深情情',
    position: '帮会学徒',
    occupation: '鸿音',
    combatPower: '302786',
  },
  {
    userName: '初闻桂堂东',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '309251',
  },
  {
    userName: '白漂',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '319575',
  },
  {
    userName: '巴巴适适大扎胩',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '303683',
  },
  {
    userName: '陈昂',
    position: '帮会学徒',
    occupation: '铁衣',
    combatPower: '301012',
  },
  {
    userName: '月锡',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '308402',
  },
  {
    userName: '如烟似雨',
    position: '帮会学徒',
    occupation: '鸿音',
    combatPower: '307781',
  },
  {
    userName: '欢子',
    position: '帮会学徒',
    occupation: '鸿音',
    combatPower: '309742',
  },
  {
    userName: '语诺',
    position: '帮会学徒',
    occupation: '鸿音',
    combatPower: '307519',
  },
  {
    userName: '小辣椒ヾ',
    position: '帮会学徒',
    occupation: '鸿音',
    combatPower: '326986',
  },
  {
    userName: '小张同学',
    position: '帮会学徒',
    occupation: '血河',
    combatPower: '319443',
  },
  {
    userName: '可爱到懵',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '299846',
  },
  {
    userName: '秋秋月',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '305058',
  },
  {
    userName: '雾吟゛',
    position: '帮会学徒',
    occupation: '龙吟',
    combatPower: '300801',
  },
  {
    userName: '不汍ゞ',
    position: '帮会学徒',
    occupation: '龙吟',
    combatPower: '305604',
  },
  {
    userName: '゛醉香诗',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '309153',
  },
  {
    userName: '花玥玥',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '307312',
  },
  {
    userName: '梦入江湖寄此生',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '311736',
  },
  {
    userName: '明月ぃ',
    position: '帮会学徒',
    occupation: '潮光',
    combatPower: '302689',
  },
  {
    userName: '秇淰',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '325133',
  },
  {
    userName: '羽小小',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '299673',
  },
  {
    userName: '笔画雲天丶',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '306373',
  },
  {
    userName: '芊菓ゝ',
    position: '帮会学徒',
    occupation: '碎梦',
    combatPower: '299841',
  },
  {
    userName: '小楼一夜又东风',
    position: '帮会学徒',
    occupation: '龙吟',
    combatPower: '320003',
  },
  {
    userName: '菲菲吖ゞ',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '300347',
  },
  {
    userName: '我就说好吃吧',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '316080',
  },
  {
    userName: '小胳膊小腿欠打',
    position: '帮会学徒',
    occupation: '九灵',
    combatPower: '305980',
  },
  {
    userName: '三娃子丶',
    position: '帮会学徒',
    occupation: '碎梦',
    combatPower: '306246',
  },
  {
    userName: '展云熙゛',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '297903',
  },
  {
    userName: '凉瑾安丶',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '319216',
  },
  {
    userName: '观海丿听澜',
    position: '帮会学徒',
    occupation: '龙吟',
    combatPower: '310852',
  },
  {
    userName: '打豆豆゜',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '308550',
  },
  {
    userName: '好甜',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '290874',
  },
  {
    userName: '你可别想指挥我',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '299323',
  },
  {
    userName: '柠乐゛',
    position: '帮会学徒',
    occupation: '碎梦',
    combatPower: '301279',
  },
  {
    userName: '七月犇犇犇',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '313893',
  },
  {
    userName: '十号',
    position: '帮会学徒',
    occupation: '铁衣',
    combatPower: '305499',
  },
  {
    userName: '小雪浓',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '304074',
  },
  {
    userName: '三月灬',
    position: '帮会学徒',
    occupation: '铁衣',
    combatPower: '310441',
  },
  {
    userName: '小怪兽ゞ',
    position: '帮会学徒',
    occupation: '血河',
    combatPower: '315294',
  },
  {
    userName: '陆景和',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '305278',
  },
  {
    userName: '洣雪灬',
    position: '帮会学徒',
    occupation: '九灵',
    combatPower: '322478',
  },
  {
    userName: '幼稚园熊大',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '303703',
  },
  {
    userName: '胖球球',
    position: '帮会学徒',
    occupation: '碎梦',
    combatPower: '326094',
  },
  {
    userName: '你女儿的男朋友',
    position: '帮会学徒',
    occupation: '龙吟',
    combatPower: '323795',
  },
  {
    userName: '一念关山゛',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '325161',
  },
  {
    userName: '等我晚安',
    position: '帮会学徒',
    occupation: '碎梦',
    combatPower: '307635',
  },
  {
    userName: '羡秋',
    position: '帮会学徒',
    occupation: '血河',
    combatPower: '301818',
  },
  {
    userName: '叶神',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '311906',
  },
  {
    userName: '清河ゝ',
    position: '帮会学徒',
    occupation: '九灵',
    combatPower: '325831',
  },
  {
    userName: '见花不见叶',
    position: '帮会学徒',
    occupation: '神相',
    combatPower: '307604',
  },
  {
    userName: '似雨',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '303065',
  },
  {
    userName: '然然加班摸鱼丶',
    position: '帮会学徒',
    occupation: '素问',
    combatPower: '293389',
  },
  {
    userName: '出羽灿灿',
    position: '帮会学徒',
    occupation: '九灵',
    combatPower: '304932',
  },
  {
    userName: 'っ゛鉳铖づ',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '295241',
  },
  {
    userName: '买米当卡',
    position: '帮会学徒',
    occupation: '血河',
    combatPower: '324832',
  },
  {
    userName: '乂爻爻乂゛',
    position: '帮会学徒',
    occupation: '玄机',
    combatPower: '319079',
  },
  {
    userName: '洛秋゛',
    position: '帮会学徒',
    occupation: '铁衣',
    combatPower: '309385',
  },
  {
    userName: '喜晴゛',
    position: '帮会学徒',
    occupation: '血河',
    combatPower: '303482',
  },
]

export default memberData